### ISSUE TITLE
Use a consistent interface for Tables where input type cannot be converted

### ISSUE THREAD

**Issue by bencottier** [invenia/FeatureTransforms.jl#12]
I'm uncertain about this. There's a more general question of what operations on Tables we want to provide, vs. leaving to the user.

Currently, we have an [`apply!` for tables](https://github.com/invenia/Transforms.jl/blob/3fe2b2718b262f99e8ac215e70e01e041fdad3ba/src/transformers.jl#L72-L86) that mutates the table columns in-place.

However this doesn't work when the input type can't be converted to the output type, e.g. from DateTime to Int for the hour-of-day transform. We could replace the column with the new type, but users should have a choice whether to do such a "strong" mutation.

Alternatively we could have an `apply!` that appends the new columns to the Table.

We could also have an `apply` that  returns the transformed columns on their own ([example](https://github.com/invenia/Transforms.jl/blob/7b2e35aebe587b858eec7b79e95be64704a513db/src/periodic.jl#L49-L55)), which gives users the most flexibility.

**Comment by nicoleepp** [comment]
I don't like

> Alternatively we could have an apply! that appends the new columns to the Table.

just because `apply!` done on Arrays would not have the same behaviour and that's confusing

For that reason I think

> We could also have an apply that returns the transformed columns on their own (example), which gives users the most flexibility.

is the best option, and let the user append the result to the table explicitly

**Comment by nicoleepp** [comment]
If we really wanted

> Alternatively we could have an apply! that appends the new columns to the Table.

It should probably be a third function, like `apply_append!(x::Table, ::Transfrom; newcolnames = [:a. :b], kwargs...)`

or

`apply!(x::Table, ::Transform; append=false, newcolnames=[:a, :b], kwargs...)` but this last one might be confusing as sometimes it would mutate the cols that exist and sometimes append

**Comment by glennmoy** [comment]
> is the best option, and let the user append the result to the table explicitly

It also gives them the flexibility to name it accordingly. Otherwise we'd have to come up with a naming convention in the package ☠️
