### ISSUE TITLE
Make LinearCombination support specifying axis key as the dims? 

### ISSUE THREAD

**Issue by nicoleepp** [invenia/FeatureTransforms.jl#13]
does this also work if passing in the axis key? e.g. `foo`, `bar`?

_Originally posted by @glennmoy in https://github.com/invenia/Transforms.jl/pull/8#discussion_r572226392_

**Comment by nicoleepp** [comment]
We are leaving this for later, as  `eachslice` is lacking `axisnames` support and it’s not going to be expected that Transforms supports it 

See https://github.com/JuliaArrays/AxisArrays.jl/issues/7

**Comment by nicoleepp** [comment]
Related to #20

**Comment by glennmoy** [comment]
stale issue
