### ISSUE TITLE
Support named dims for `dims` keyword  argument

### ISSUE THREAD

**Issue by bencottier** [invenia/FeatureTransforms.jl#20]
To use a consistent convention for `dims` (#18), we currently have to "invert" the value passed into the `dims` keyword argument to the array-based `apply!`, so that `eachslice` gives the expected result. For example `dims=2` becomes `dims=1` and `dims=3` becomes `dims=[1, 2]`. Basically we can use `setdiff(1:ndims(array), dims)` to accomplish that.

The solution isn't so straightforward for named dims, because the method to get the list of dim names is not universal. `KeyedArray` supports `dimnames(A)` but `AxisArray` does not, instead using `axisnames`. One workaround is `dimnames(wrapdims(::AxisArray))` but that requires adding `AxisKeys` as a dependency. 

Some have suggested that support for `AxisArrays` should be dropped entirely, or included in an auxiliary package - then we could rely on `dimnames`.

**Comment by glennmoy** [comment]
"Not having named dims limits the usefulness of using a KeyedArray as opposed to just an AbstractArray"

**Comment by nicoleepp** [comment]
I personally vote that adding the dependency on some of the underlying packages might be worth having named dims for

**Comment by bencottier** [comment]
Are named dims actually prevented anywhere now? I think it may only be keys for `inds` now. I just checked named `dims` works for `MeanStdScaling` on `KeyedArray`.

**Comment by bencottier** [comment]
> I personally vote that adding the dependency on some of the underlying packages might be worth having named dims for

I don't have a good sense of the cost of adding the dependency. On the face of it, it seems worthwhile if we can't find any other non-hack way.

**Comment by glennmoy** [comment]
> Are named `dims` actually prevented anywhere now? I think it may only be keys for `inds` now. I just checked named `dims` works for `MeanStdScaling` on `KeyedArray`.

They are not in fact. We've added explicit tests in https://github.com/invenia/FeatureTransforms.jl/pull/62
