### ISSUE TITLE
Support slices over multiple dims

### ISSUE THREAD

**Issue by bencottier** [invenia/FeatureTransforms.jl#21]
Note: there are different meanings of `dims` (#18 ), but the fundamental issue is that `eachslice` only supports single dimensions.

The problem arises in the following example. I want to apply `MeanStdScaling`, which internally computes `mean(data; dims=3)` and `std(data; dims=3)` in the sense of _reducing_ the data on dimension 3, in a 3D array. Currently, to do that, `eachslice` would need to take `dims=[1, 2]`, but it only supports single dimensions. Therefore we might need to move away from `eachslice`.

**Comment by glennmoy** [comment]
no longer applies
